### ISSUE TITLE
url patterns and string view removed In Django 1.10

### ISSUE THREAD

**Issue by kevinmickey** [danfairs/django-lazysignup#49]
> /.../lib/python2.7/site-packages/lazysignup/urls.py:9: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got convert). Pass the callable instead.
>   url(r'^$', 'convert', name='lazysignup_convert'),
> 
> /.../lib/python2.7/site-packages/lazysignup/urls.py:12: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
>   name='lazysignup_convert_done'),

**Comment by danfairs** [comment]
Thanks! Am I right in thinking that's with the latest Django, 1.9.6?

**Comment by kevinmickey** [comment]
Yes, thanks I should have included that.

**Comment by danfairs** [comment]
Fixed in 5394660a2fa0642a0f534e49a0b9dca62d88914c
