### ISSUE TITLE
Approach for custom user models with email as username?

### ISSUE THREAD

**Issue by dwjp** [danfairs/django-lazysignup#52]
Apologies if I'm missing something obvious, but what's the suggested approach when using a custom user model that uses email as the username? 

This appears to be hardcoded in models as `username_field = 'username'`. I'm using `authtools. User` which sets `USERNAME_FIELD = 'email'`, so seems to be a matter of plumbing that in?

**Comment by dwjp** [comment]
For the moment I've done this terrible thing (still testing):

```
from lazysignup.models import LazyUserManager, LazyUser
from lazysignup.backends import LazySignupBackend
from authtools.models import User

def custom_lazy_signup_authenticate(self, username=None):
    user_class = LazyUser.get_user_class()
    try:
        return user_class.objects.get(email=username)   # Monkey patch - changed username to email to suit authtools User model
    except user_class.DoesNotExist:
        return None

LazyUserManager.username_field = User.USERNAME_FIELD
LazySignupBackend.authenticate = custom_lazy_signup_authenticate
```

I think a USERNAME_FIELD setting would be the proper way to do this?

**Comment by danfairs** [comment]
Hi there! The intent here originally was to override `username_field` in subclasses. So if you're already using a custom user, you should just override that attribute. (If you're pulling it from settings, then doing it in a property might be appropriate).

I haven't had time to actually try this, so do come back if that doesn't work!

Also happy to accept patches to improve the dev experience here - lazysignup predates custom user models, and I'm aware there are some rough edges. 

(I'm not a great fan of introducing yet more settings though, hence the preference for Python-level configuration.)

**Comment by danfairs** [comment]
Think this is probably (long!) superceded by #56, so closing.
