### ISSUE TITLE
Django: Contribute to third party app django-lazysignup

### ISSUE THREAD

**Issue by sufian07** [danfairs/django-lazysignup#53]
I want to contribute to django-lazysignup a django third party app. I tried so far the following steps

I set up a regular django app named custom-user
I used virtualenv and install required library on virtualenv
I fork and clone the github repository of django-lazysignup
I run the sudo pip install -e /path/to/folder/django-lazysignup command
I am trying to run command python manage.py makemigrations on custom-user project but it showing ImportError: No module named 'lazysignup'.

Any help will be appreciated

N:B: I also asked on stackoverflow http://stackoverflow.com/questions/40319447/django-contribute-to-third-party-app-django-lazysignup

**Comment by danfairs** [comment]
It looks like someone jumped in your question on SO, so will close this as it doesn't seem to be a problem with `lazysignup` itself.
