### ISSUE TITLE
Delete LazyUsers after a certain period

### ISSUE THREAD

**Issue by othreecodes** [danfairs/django-lazysignup#55]
Hello, Im using this module for a project that requires me to keep track of "real" users in the database. Is there a way to remove lazy users say after 2 or 3 days.

**Comment by danfairs** [comment]
There's a `delete_lazy_users` management command - this works for common cases, but you should review it to make sure it's suitable for your setup before running it!

https://github.com/danfairs/django-lazysignup/blob/master/lazysignup/management/commands/remove_expired_users.py

You should run that command (or your equivalent) periodically, perhaps via `cron`.
