### ISSUE TITLE
Django 2.0+ `on_delete` compatibility

### ISSUE THREAD

**Issue by glowka** [danfairs/django-lazysignup#61]
Upgrading Django to 2.0+ version causes an error:
```
File "/home/tomek/Project/pp/env/lib/python3.6/site-packages/lazysignup/models.py", line 80, in <module>
    class LazyUser(models.Model):
File "/home/tomek/Project/pp/env/lib/python3.6/site-packages/lazysignup/models.py", line 81, in LazyUser
    user = models.OneToOneField(constants.LAZYSIGNUP_USER_MODEL)
TypeError: __init__() missing 1 required positional argument: 'on_delete'

```

Which seems to be caused by the change mentioned in [2.0 release notes](https://docs.djangoproject.com/en/2.1/releases/2.0/#features-removed-in-2-0):

> The `on_delete` argument for `ForeignKey` and `OneToOneField` is now required in models and migrations. Consider squashing migrations so that you have fewer of them to update.

**Comment by danfairs** [comment]
This was fixed in #60.
